# Generated by Django 4.1.1 on 2022-09-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_autor_options_livros"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Livros",
            new_name="Livro",
        ),
    ]
