# Generated by Django 4.1.1 on 2022-09-18 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_livros_livro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="editora",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="core.editora",
            ),
        ),
    ]
