# Generated by Django 4.1.1 on 2022-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_livro_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="core.autor"),
        ),
    ]
